---
sidebar: sidebar 
permalink: reference-instance-types.html 
keywords: BlueXP classification, installation, deployment, instance, virtual machine, cpu, ram, memory, disk, capacity 
summary: 'Il software di classificazione dei dati deve essere eseguito su un host che soddisfi specifici requisiti del sistema operativo, requisiti di RAM, requisiti software e così via.  Quando si distribuisce la classificazione dei dati nel cloud, si consiglia di utilizzare un sistema con caratteristiche "grandi" per una funzionalità completa.' 
---
= Tipi di istanza NetApp Data Classification supportati
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Data Classification software deve essere eseguito su un host che soddisfi specifici requisiti di sistema operativo, requisiti di RAM e requisiti software. Quando si implementa Data Classification nel cloud, si consiglia di utilizzare un sistema con caratteristiche "large" per la piena funzionalità.

Nelle tabelle seguenti, se il sistema contrassegnato come "default" non è disponibile nella regione in cui si sta installando Data Classification, verrà distribuito il tipo di istanza successivo elencato nella tabella.



[[aws-instance-types]]
== Tipi di istanza AWS

[cols="20,30,25"]
|===
| Dimensioni del sistema | Specifiche | Tipo di istanza 


| Extra Large | 32 CPU, 128 GB di RAM, 1 TiB gp3 SSD | https://aws.amazon.com/ec2/instance-types/m6i/["m6i.8xlarge"^](predefinito) 


| Grande | 16 CPU, 64 GB di RAM, SSD da 500 GiB | https://aws.amazon.com/ec2/instance-types/m6i/["m6i.4xlarge"^](predefinito) m6a.4xlarge m5a.4xlarge m5.4xlarge m4.4xlarge 
|===


[[azure-instance-types]]
== Tipi di istanza di Azure

[cols="20,30,25"]
|===
| Dimensioni del sistema | Specifiche | Tipo di istanza 


| Extra Large | 16 CPU, 64 GB di RAM, disco del sistema operativo (2.048 GiB, min 250 MB/s throughput) e disco dati (SSD da 1 TiB, min 750 MB/s throughput) | https://learn.microsoft.com/en-us/azure/virtual-machines/sizes/general-purpose/dv5-series["Standard_D32s_v5 o Standard_D32_v5"^] 


| Grande | 16 CPU, 64 GB di RAM, SSD da 500 GiB | link:https://learn.microsoft.com/en-us/azure/virtual-machines/sizes/general-purpose/dsv5-series?tabs=sizebasic["Standard_D16_v5 o Standard_D16s_v5"^] (predefinito) 
|===


[[gcp-instance-types]]
== Tipi di istanza GCP

[cols="20,30,25"]
|===
| Dimensioni del sistema | Specifiche | Tipo di istanza 


| Grande | 16 CPU, 64 GB di RAM, SSD da 500 GiB | https://cloud.google.com/compute/docs/general-purpose-machines#n2_machines["n2-standard-16"^](predefinito) n2d-standard-16 n1-standard-16 
|===