---
sidebar: sidebar 
permalink: task-deploy-overview.html 
keywords: cloud compliance, data sense, get started, deploy cloud data sense, outbound internet, endpoints, cloud compliance internet, web browser connectivity, cloud compliance access, privacy, compliance, bluexp classification 
summary: Pianifica quale distribuzione di NetApp Data Classification soddisfa le tue esigenze. 
---
= Scegli il metodo di implementazione di NetApp Data Classification
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile implementare NetApp Data Classification in diversi modi. Esamina i metodi disponibili per scegliere quello più adatto alle tue esigenze.

* link:task-deploy-cloud-compliance.html["Distribuisci nel cloud utilizzando la console"] . La Console distribuisce l'istanza di classificazione dei dati nella stessa rete del provider cloud dell'agente della Console.
* link:task-deploy-compliance-onprem.html["Installa su un host Linux con accesso a Internet"] . Installa Data Classification su un host Linux nella tua rete o su un host Linux nel cloud che abbia accesso a Internet.  Questo tipo di installazione può essere una buona opzione se si preferisce eseguire la scansione dei sistemi ONTAP locali utilizzando un'istanza di classificazione dei dati anch'essa ubicata in sede, sebbene non sia un requisito.
* link:task-deploy-compliance-dark-site.html["Installa su un host Linux in un sito locale senza accesso a Internet"], nota anche come _modalità privata_. Questo tipo di installazione, che utilizza uno script di installazione, non ha connettività con il livello SaaS della console.



TIP: Per le implementazioni VMware on-premises vSphere, NetApp Data Classification supporta una versione semplificata link:task-deploy-ova.html["implementazione con OVA"].



== Script di installazione locale

Sia l'installazione su un host Linux con accesso a Internet sia l'installazione locale su un host Linux senza accesso a Internet utilizzano uno script di installazione. Lo script inizia verificando se il sistema e l'ambiente soddisfano i prerequisiti. Se i prerequisiti sono soddisfatti, l'installazione ha inizio.

È disponibile un pacchetto software separato per verificare la readiness del tuo Linux. Per eseguire il pacchetto di verifica, consulta link:task-test-linux-system.html["verifica che il tuo host Linux sia pronto per installare Data Classification"].
