---
sidebar: sidebar 
permalink: task-active-directory.html 
keywords: active directory, ad, data sense, cloud data sense 
summary: È possibile integrare un Active Directory globale con NetApp Data Classification per migliorare i risultati che Data Classification riporta sui proprietari dei file e sugli utenti e gruppi che hanno accesso ai file. 
---
= Integra Active Directory con NetApp Data Classification
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile integrare un Active Directory globale con NetApp Data Classification per migliorare i risultati che Data Classification riporta sui proprietari dei file e sugli utenti e gruppi che hanno accesso ai file.

Quando si configurano determinate origini dati (elencate di seguito), è necessario immettere le credenziali di Active Directory affinché Data Classification esegua la scansione dei volumi CIFS.  Questa integrazione fornisce alla classificazione dei dati i dettagli sul proprietario del file e sulle autorizzazioni per i dati che risiedono in tali origini dati.  Le credenziali di Active Directory immesse per tali origini dati potrebbero essere diverse dalle credenziali di Active Directory globali immesse qui.  La classificazione dei dati cercherà in tutte le Active Directory integrate i dettagli degli utenti e delle autorizzazioni.

Questa integrazione fornisce informazioni aggiuntive nelle seguenti posizioni nella Classificazione dei dati:

* Puoi usare il "Proprietario del file"link:task-investigate-data.html["filtro"] e visualizza i risultati nei metadati del file nel riquadro Indagine.  Invece del proprietario del file contenente il SID (Security IDentifier), viene inserito il nome utente effettivo.
+
È inoltre possibile visualizzare maggiori dettagli sul proprietario del file: nome dell'account, indirizzo e-mail e nome dell'account SAM, oppure visualizzare gli elementi di proprietà di tale utente.

* Puoi visualizzare link:task-investigate-data.html["permessi completi del file"] per ogni file e directory quando selezioni il pulsante "Visualizza tutte le autorizzazioni".
* Nellink:task-controlling-governance-data.html["Dashboard di governance"] , il pannello Autorizzazioni aperte mostrerà un livello di dettaglio maggiore sui tuoi dati.



NOTE: I SID degli utenti locali e i SID di domini sconosciuti non vengono tradotti nel nome utente effettivo.



[[supported-data-sources]]
== Fonti dati supportate

Un'integrazione di Active Directory con Data Classification può identificare i dati dalle seguenti origini dati:

* Azure NetApp Files
* Cloud Volumes ONTAP
* FSx per ONTAP
* Sistemi ONTAP on-premise




[[connect-to-your-active-directory-server]]
== Connettiti al tuo server Active Directory

Dopo aver distribuito Data Classification e attivato la scansione sulle origini dati, è possibile integrare Data Classification con Active Directory.  È possibile accedere ad Active Directory tramite un indirizzo IP del server DNS o un indirizzo IP del server LDAP.

Le credenziali di Active Directory possono essere di sola lettura, ma fornendo le credenziali di amministratore si garantisce che Data Classification possa leggere tutti i dati che richiedono autorizzazioni elevate.  Le credenziali vengono archiviate nell'istanza di classificazione dei dati.

Per CIFS volumi/condivisioni file, se si desidera garantire che gli orari di "ultimo accesso" ai file non vengano modificati dalle scansioni di Data Classification, l'utente deve disporre dell'autorizzazione di scrittura sugli attributi. Se possibile, si consiglia di includere l'utente configurato in Active Directory in un gruppo padre dell'organizzazione che disponga delle autorizzazioni per tutti i file.

.Requisiti
* È necessario che sia già stata configurata una Active Directory per gli utenti della propria azienda.
* È necessario disporre delle informazioni per Active Directory:
+
** Indirizzo IP del server DNS o più indirizzi IP
+
O

+
Indirizzo IP del server LDAP o più indirizzi IP

** Nome utente e password per accedere al server
** Nome di dominio (nome di Active Directory)
** Se stai utilizzando LDAP sicuro (LDAPS) o meno
** Porta del server LDAP (in genere 389 per LDAP e 636 per LDAP sicuro)


* Le seguenti porte devono essere aperte per la comunicazione in uscita da parte dell'istanza di classificazione dei dati:
+
[cols="20,20,30,30"]
|===
| Protocollo | Porta | Destinazione | Scopo 


| TCP e UDP | 389 | Directory attiva | LDAP 


| TCP | 636 | Directory attiva | LDAP su SSL 


| TCP | 3268 | Directory attiva | Catalogo globale 


| TCP | 3269 | Directory attiva | Catalogo globale su SSL 
|===


.Passi
. In Classificazione dati, seleziona **Configurazione**.
. Passa alla scheda **Impostazioni**.
. Nella sezione Active Directory, selezionare **Aggiungi**.
. Nella finestra di dialogo Connetti ad Active Directory, immettere i dettagli di Active Directory e quindi selezionare *Connetti*.
+
Se necessario, è possibile aggiungere più indirizzi IP selezionando *Aggiungi IP*.

+
La classificazione dei dati si integra con Active Directory e una nuova sezione viene aggiunta alla pagina Configurazione.





[[manage-your-active-directory-integration]]
== Gestisci la tua integrazione con Active Directory

Se devi modificare dei valori nell'integrazione con Active Directory, devi aggiornare la configurazione di Active Directory in Data Classification. Torna al menu **Configuration** in Data Classification e passa alla scheda settings per apportare le modifiche.

È inoltre possibile eliminare l'integrazione selezionando il pulsante **Rimuovi** in Active Directory.
