= Versione 1.39
:allow-uri-read: 




=== Versione 1.39

Questa versione BlueXP classification aggiorna il processo di esportazione per il report di indagine sui dati.  Questo aggiornamento dell'esportazione è utile per eseguire analisi aggiuntive sui dati, creare visualizzazioni aggiuntive sui dati o condividere i risultati dell'indagine sui dati con altri.

In precedenza, l'esportazione del report di indagine sui dati era limitata a 10.000 righe.  Con questa versione il limite è stato rimosso, così puoi esportare tutti i tuoi dati.  Questa modifica ti consente di esportare più dati dai tuoi report di indagine sui dati, garantendoti maggiore flessibilità nell'analisi dei dati.

È possibile scegliere l'ambiente di lavoro, i volumi, la cartella di destinazione e il formato JSON o CSV.  Il nome del file esportato include un timestamp per aiutarti a identificare quando i dati sono stati esportati.

Gli ambienti di lavoro supportati includono:

* Cloud Volumes ONTAP
* FSx per ONTAP
* ONTAP
* Condividi gruppo


L'esportazione dei dati dal report di indagine sui dati presenta le seguenti limitazioni:

* Il numero massimo di record da scaricare è 500 milioni per tipo (file, directory e tabelle)
* Si prevede che l'esportazione di un milione di record richiederà circa 35 minuti.


Per i dettagli sull'indagine dei dati e sul rapporto, vedere https://docs.netapp.com/us-en/data-services-data-classification/task-investigate-data.html["Esamina i dati archiviati nella tua organizzazione"] .
