= Versione 1.40
:allow-uri-read: 




=== Versione 1.40

Questa versione BlueXP classification include i seguenti aggiornamenti.

.Supporto per RHEL 9.5
Questa versione fornisce supporto per Red Hat Enterprise Linux v9.5 oltre alle versioni supportate in precedenza.  Ciò è applicabile a qualsiasi installazione manuale in sede della BlueXP classification, comprese le distribuzioni in dark site.

I seguenti sistemi operativi richiedono l'utilizzo del motore container Podman e la versione BlueXP classification 1.30 o successiva: Red Hat Enterprise Linux versione 8.8, 8.10, 9.0, 9.1, 9.2, 9.3, 9.4 e 9.5.

.Dare priorità alle scansioni di sola mappatura
Quando si eseguono scansioni di sola mappatura, è possibile dare priorità alle scansioni più importanti.  Questa funzionalità è utile quando si hanno molti ambienti di lavoro e si desidera garantire che le scansioni ad alta priorità vengano completate per prime.

Per impostazione predefinita, le scansioni vengono messe in coda in base all'ordine in cui vengono avviate.  Grazie alla possibilità di dare priorità alle scansioni, è possibile spostarle in cima alla coda.  È possibile dare priorità a più scansioni.  La priorità viene assegnata in base all'ordine "first-in, first-out", ovvero la prima scansione a cui si dà priorità viene spostata in cima alla coda; la seconda scansione a cui si dà priorità diventa la seconda nella coda e così via.

La priorità viene concessa una sola volta.  Le nuove scansioni automatiche dei dati di mappatura avvengono nell'ordine predefinito.

La priorità è limitata alink:https://docs.netapp.com/us-en/bluexp-classification/concept-classification.html["scansioni solo di mappatura"^] ; non è disponibile per le scansioni di mappatura e classificazione.

Per ulteriori informazioni, consultare link:https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#prioritize-scans["Dare priorità alle scansioni"^] .

.Riprova tutte le scansioni
La BlueXP classification supporta la possibilità di ripetere in batch tutte le scansioni non riuscite.

È possibile ripetere le scansioni in un'operazione batch con la funzione **Riprova tutto**.  Se le scansioni di classificazione non riescono a causa di un problema temporaneo, ad esempio un'interruzione di rete, è possibile riprovare tutte le scansioni contemporaneamente premendo un pulsante anziché riprovarle singolarmente.  È possibile ripetere la scansione tutte le volte che si desidera.

Per riprovare tutte le scansioni:

. Dal menu BlueXP classification , selezionare *Configurazione*.
. Per riprovare tutte le scansioni non riuscite, seleziona *Riprova tutte le scansioni*.


.Miglioramento della precisione del modello di categorizzazione
L'accuratezza del modello di apprendimento automatico perlink:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-sensitive-personal-datapredefined-categories["categorie predefinite"] è migliorato dell'11%.
