= Versione 1.52
:allow-uri-read: 




=== Versione 1.52

.Validazione delle risorse
Per garantire l'affidabilità, Data Classification ora convalida la memoria disponibile e le risorse del disco durante le scansioni, la generazione di report e le azioni. Quando l'utilizzo della memoria supera il 95% o lo spazio su disco scende al di sotto di 6 GB, Data Classification sospende automaticamente le operazioni. Le operazioni riprendono quando le risorse sono sufficienti.

Per monitorare le risorse del sistema, vedere link:https://docs.netapp.com/us-en/data-services-data-classification/task-health-monitor.html["Monitorare lo stato di salute della classificazione dei dati"^].

.Limite aumentato per copia e spostamento
Le funzioni di copia e spostamento sono ora supportate per le destinazioni CIFS. Il limite di dimensione per file per entrambe le azioni è aumentato a 1 GB dal precedente limite di 50 MB. I limiti operativi per entrambe le azioni sono aumentati a 1 TB o 5 milioni di file.

Per ulteriori informazioni, consultare link:https://docs.netapp.com/us-en/data-services-data-classification/task-investigate-data.html["Indagare i dati"^].

.Autorizzazioni di configurazione dell'integrazione di Active Directory
Le modifiche alle impostazioni di integrazione di Active Directory (AD) in Data Classification sono ora riservate agli amministratori. I visualizzatori non hanno più la possibilità di modificare le impostazioni di AD.

Per ulteriori informazioni sul ruolo di Classification viewer, vedere link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html#data-service-roles["Ruoli del servizio dati"^].

.Supporto proxy trasparente
Data Classification ora supporta configurazioni proxy trasparenti, consentendo una distribuzione più fluida in ambienti di rete con proxy o con restrizioni.

Per ulteriori informazioni sulla distribuzione in ambienti con restrizioni, vedere link:https://docs.netapp.com/us-en/data-services-data-classification/task-deploy-compliance-dark-site.html["Installa NetApp Data Classification su un host Linux senza accesso a Internet"^].
