= Pagina di configurazione migliorata
:allow-uri-read: 




[[improved-configuration-page]]
=== Pagina di configurazione migliorata

Data Classification ha aggiornato e migliorato la pagina di configurazione, offrendo un'esperienza d'uso ottimizzata per la gestione delle impostazioni, dei sistemi, l'attivazione delle scansioni e il monitoraggio dello stato di salute del sistema. La nuova pagina di configurazione ripropone le funzionalità esistenti in un formato più intuitivo, con l'aggiunta della possibilità di filtrare i sistemi per tipo, stato di errore e stato di scansione. La nuova pagina fornisce inoltre un riepilogo dei sistemi connessi e una panoramica delle scansioni attive e configurate.

Rivedi un link:https://youtu.be/_8YJ3KyZ7nI["video dimostrativo"^]. Per ulteriori informazioni, consulta link:https://docs.netapp.com/us-en/data-services-data-classification/task-scanning-overview.html["Analizza le fonti di dati con Data Classification"^].



[[compliance-admin-iam-role]]
=== Ruolo di amministratore della conformità IAM

La classificazione dei dati ora supporta un ruolo di amministratore della conformità per gestire le autorizzazioni nella classificazione dei dati. Il ruolo di amministratore della conformità non ha accesso a risorse quali agenti della Console e aree di lavoro. Gli utenti con il ruolo di amministratore della conformità devono essere associati ad almeno un altro ruolo.

Durante l'installazione di Data Classification, è necessario disporre del ruolo di amministratore della piattaforma Console o del ruolo di amministratore della conformità.

Se sei già un utente registrato, l'accesso dovrebbe continuare normalmente. Ad esempio, un ruolo sulla piattaforma che include un ruolo di amministratore di cartella o di progetto ha già accesso.

Per ulteriori informazioni, consultare link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-data-classification.html["Ruoli di classificazione dei dati"^].



[[deploy-data-classification-with-ova]]
=== Implementa la classificazione dei dati con OVA

NetApp Data Classification ora supporta la distribuzione con VMware Open Virtual Appliance (OVA), offrendo una strategia di distribuzione semplificata per ambienti VMware vSphere on-premises.

Per ulteriori informazioni, consultare link:https://docs.netapp.com/us-en/data-services-data-classification/task-deploy-ova.html["Implementa la classificazione dei dati con OVA"^].
