= Versione 1.50
:allow-uri-read: 




=== Versione 1.50

Questa versione di Data Classification include correzioni di bug e i seguenti aggiornamenti:

.Miglioramenti della classificazione personalizzata
Data Classification ora supporta la creazione di categorie personalizzate per i tuoi dati. È possibile caricare file per perfezionare un modello di intelligenza artificiale che Data Classification utilizza per applicare il marcatore di categoria ai dati. L'interfaccia per tutte le classificazioni personalizzate è stata migliorata.

Per maggiori informazioni, vedere link:https://docs.netapp.com/us-en/data-services-data-classification/task-custom-classification.html["Crea una classificazione personalizzata"^].

.Definizione di dati obsoleti personalizzati
La classificazione dei dati ora consente di personalizzare la definizione dei dati obsoleti in modo che si adatti alle esigenze della tua organizzazione. In precedenza, per dati obsoleti si intendevano tutti i dati la cui ultima modifica risaliva a tre anni prima. Ora è possibile identificare i dati obsoleti in base alla data dell'ultimo accesso o dell'ultima modifica; il periodo di tempo può variare da 6 mesi a 10 anni fa.

Per maggiori informazioni, vedere link:https://docs.netapp.com/us-en/data-services-data-classification/task-stale-data.html["Personalizza la definizione dei dati obsoleti"^].

.Prestazioni migliorate
I tempi di caricamento per tutte le pagine della Classificazione dati, del report di mappatura dati e dei filtri nella pagina Indagine sono stati ridotti.

.Tempo stimato per i rapporti di indagine
Quando si scarica un rapporto di indagine, la classificazione dei dati ora visualizza il tempo stimato necessario per il completamento del download.
